# Site settings
title: SYS49152
email: storm@sys49152.net
description: "Just a space to put whatever i feel like :)"
baseurl: ""
url: "http://sys49152.net"
twitter_username: 
github_username: ricferr

# Build settings
markdown: kramdown
permalink: pretty
